openapi: 3.0.3

info:
  title: Neessi API
  description: Neessi API for integration with EU's EESSI framework
  contact:
    name: vegard.lundeberg.hillestad@nav.no
  version: v4.3

servers:
  - url: '/api'

tags:
  - name: "S040"
    description: >-
      Integrate with version 4.3 of the CDM framework

paths:
  '/v4.3/cases/{internationalId}/documents/s040/{setId}':
    $ref: 'v4.3/documents/s040/operations_root.yaml'
